#' use ggplot2 colors
#' 
#' generates the code for getting some ggplot2 colors
#' 
#' @export
#' @return string
ft_ggplot2_colors = function()
{
  cat('ggplot2::scale_color_discrete()$palette(n)', sep = "\n")
}

#' rotate axis labels
#' 
#' Gives me the code to rotate axis labels.
#' 
#' @export
#' @return string
ft_rotate_axis_labels = function()
{
  cat('scale_x_discrete(guide = guide_axis(angle = 90))',
      'theme(axis.text.x=element_text(angle = 90)',
      'coord_flip()', sep = "\n\n")
}


#' add numbers to figure files
#' 
#' Given that `rmd` and `qmd` chunks are **normally** run sequentially, figures
#' should be generated in order that they are presented in the document. Therefore,
#' we should be able to roughly match them up with numbering generated by cross-referencing
#' using the modified times.
#' 
#' @param figure_directory the directory containing figure files
#' @param start_count what number starts the counting
#' @param count_location should the count be a `prefix` or `suffix`?
#' @param skip_numbers should any numbers be skipped due to inserting from a different location?
#' @param regexp what regex should be used to grab files
#' 
#' @export
#' @return NULL
ft_add_figure_numbers = function(figure_directory = ".",
                                 start_count = 1,
                                 count_location = "prefix",
                                 skip_numbers = NULL,
                                 regexp = "jpg$|png$|svg$")
{
  figure_files = fs::dir_ls(figure_directory, regexp = regexp)
  file_data = fs::file_info(figure_files)
  file_data$bare_path = fs::path_dir(file_data$path)
  file_data$file_no_ext = fs::path_ext_remove(fs::path_file(file_data$path))
  file_data$ext = fs::path_ext(file_data$path)
  
  mod_time = file_data |>
    dplyr::select(tidyselect::all_of(c("modification_time", "file_no_ext"))) |>
    dplyr::group_by(.data$file_no_ext) |>
    dplyr::slice_head(n = 1) |>
    dplyr::ungroup() |>
    dplyr::arrange(.data$modification_time) |>
    dplyr::mutate(figure_number = seq_len(dplyr::n()))
  
  if (!is.null(skip_numbers)) {
    # do something
  }
  
  file_data = dplyr::left_join(file_data, mod_time |> dplyr::select(tidyselect::all_of(c("file_no_ext", "figure_number"))), by = "file_no_ext")
  if (count_location %in% "prefix") {
    file_data$new_file = paste0("Figure_", file_data$figure_number, "_", file_data$file_no_ext, ".", file_data$ext)
  } else if (count_location %in% "suffix") {
    file_data$new_file = paste0(file_data$file_no_ext, "_Figure_", file_data$figure_number, ".", file_data$ext)
  }
  file_data$new_path = fs::path(file_data$bare_path, file_data$new_file)
  
  fs::file_move(file_data$path, file_data$new_path)
  file_data[, c("path", "new_path")]
}
